var searchData=
[
  ['addcalibrationimage',['addCalibrationImage',['../classkitrokopter_1_1APICamera.html#a56ca7cb7c6071a78beed13ae3b5ec170',1,'kitrokopter::APICamera']]],
  ['addcamera',['addCamera',['../classkitrokopter_1_1APICameraSystem.html#a9aa2aad5d12833d27df3bbe33e8385ca',1,'kitrokopter::APICameraSystem']]],
  ['addcameralistener',['addCameraListener',['../classkitrokopter_1_1APICamera.html#afbbfa308ee20b456963e143cf872504c',1,'kitrokopter::APICamera']]],
  ['addimagelistener',['addImageListener',['../classkitrokopter_1_1APICamera.html#a513c8af48151af198b706407304e56b7',1,'kitrokopter::APICamera']]],
  ['addmessagelistener',['addMessageListener',['../classkitrokopter_1_1API.html#a3b8d26425b25a729626764766eab17a2',1,'kitrokopter::API']]],
  ['addquadcopterlistener',['addQuadcopterListener',['../classkitrokopter_1_1APIQuadcopter.html#a09537ac1f3d1d75c616ad6bc1ef6aaca',1,'kitrokopter::APIQuadcopter']]],
  ['announce',['announce',['../classkitrokopter_1_1API.html#a08ca9e31f48bb0dd60083200f0de6be4',1,'kitrokopter::API']]],
  ['api',['API',['../classkitrokopter_1_1API.html#a9cc995fc23f4561b6f96c5c5d85803b2',1,'kitrokopter::API']]],
  ['api',['API',['../classkitrokopter_1_1API.html',1,'kitrokopter']]],
  ['api_2ecpp',['API.cpp',['../API_8cpp.html',1,'']]],
  ['api_2ehpp',['API.hpp',['../API_8hpp.html',1,'']]],
  ['apicalibrationdata',['APICalibrationData',['../classkitrokopter_1_1APICalibrationData.html',1,'kitrokopter']]],
  ['apicalibrationdata',['APICalibrationData',['../classkitrokopter_1_1APICalibrationData.html#a577a3df076acdd05467ee3167d89982d',1,'kitrokopter::APICalibrationData']]],
  ['apicalibrationdata_2ehpp',['APICalibrationData.hpp',['../APICalibrationData_8hpp.html',1,'']]],
  ['apicamera',['APICamera',['../classkitrokopter_1_1APICamera.html#a05e6722902fcc8761a9b70ee6051ed6e',1,'kitrokopter::APICamera::APICamera()'],['../classkitrokopter_1_1APICamera.html#af611eff528edb5027f8359392e82bf54',1,'kitrokopter::APICamera::APICamera(uint32_t newId)'],['../classkitrokopter_1_1APICamera.html#a79ee142048795d8367a3f48c815485bb',1,'kitrokopter::APICamera::APICamera(uint32_t newId, uint64_t newHardwareId)']]],
  ['apicamera',['APICamera',['../classkitrokopter_1_1APICamera.html',1,'kitrokopter']]],
  ['apicamera_2ecpp',['APICamera.cpp',['../APICamera_8cpp.html',1,'']]],
  ['apicamera_2ehpp',['APICamera.hpp',['../APICamera_8hpp.html',1,'']]],
  ['apicameralistener',['APICameraListener',['../classkitrokopter_1_1APICameraListener.html',1,'kitrokopter']]],
  ['apicameralistener_2ehpp',['APICameraListener.hpp',['../APICameraListener_8hpp.html',1,'']]],
  ['apicamerasystem',['APICameraSystem',['../classkitrokopter_1_1APICameraSystem.html',1,'kitrokopter']]],
  ['apicamerasystem',['APICameraSystem',['../classkitrokopter_1_1APICamera.html#a09a6cd9e79a63c35dc2c3c4ab275d96a',1,'kitrokopter::APICamera::APICameraSystem()'],['../classkitrokopter_1_1APICameraSystem.html#a3a64722f86e36b63fc5c95ffdb7a4bd5',1,'kitrokopter::APICameraSystem::APICameraSystem()']]],
  ['apicamerasystem_2ecpp',['APICameraSystem.cpp',['../APICameraSystem_8cpp.html',1,'']]],
  ['apicamerasystem_2ehpp',['APICameraSystem.hpp',['../APICameraSystem_8hpp.html',1,'']]],
  ['apicameraupdateevent',['APICameraUpdateEvent',['../classkitrokopter_1_1APICameraUpdateEvent.html',1,'kitrokopter']]],
  ['apicameraupdateevent_2ehpp',['APICameraUpdateEvent.hpp',['../APICameraUpdateEvent_8hpp.html',1,'']]],
  ['apierrormessage',['apiErrorMessage',['../classkitrokopter_1_1APIMessageListener.html#a287b48703ab240ad8be0e5fe7f74a48c',1,'kitrokopter::APIMessageListener']]],
  ['apiformation',['APIFormation',['../classkitrokopter_1_1APIFormation.html',1,'kitrokopter']]],
  ['apiformation',['APIFormation',['../classkitrokopter_1_1APIFormation.html#a88d3b4740d8eac23730a21b018af16d1',1,'kitrokopter::APIFormation::APIFormation()'],['../classkitrokopter_1_1APIFormation.html#a811e37015260d77ea728b5ff734a29ca',1,'kitrokopter::APIFormation::APIFormation(std::vector&lt; Vector &gt; newQuadcopterPositions, uint16_t newMinDistance)']]],
  ['apiformation_2ecpp',['APIFormation.cpp',['../APIFormation_8cpp.html',1,'']]],
  ['apiformation_2ehpp',['APIFormation.hpp',['../APIFormation_8hpp.html',1,'']]],
  ['apiimagelistener',['APIImageListener',['../classkitrokopter_1_1APIImageListener.html',1,'kitrokopter']]],
  ['apiimagelistener_2ehpp',['APIImageListener.hpp',['../APIImageListener_8hpp.html',1,'']]],
  ['apiinfomessage',['apiInfoMessage',['../classkitrokopter_1_1APIMessageListener.html#a0fbd82b4350c7485b091261d66f814d9',1,'kitrokopter::APIMessageListener']]],
  ['apimessagelistener',['APIMessageListener',['../classkitrokopter_1_1APIMessageListener.html',1,'kitrokopter']]],
  ['apimessagelistener_2ehpp',['APIMessageListener.hpp',['../APIMessageListener_8hpp.html',1,'']]],
  ['apiquadcopter',['APIQuadcopter',['../classkitrokopter_1_1APIQuadcopter.html',1,'kitrokopter']]],
  ['apiquadcopter',['APIQuadcopter',['../classkitrokopter_1_1APIQuadcopter.html#adcf98964fd113297376334d5c90ff552',1,'kitrokopter::APIQuadcopter::APIQuadcopter()'],['../classkitrokopter_1_1APIQuadcopter.html#a50445a07dab8f3c3403cebc563f8a2cd',1,'kitrokopter::APIQuadcopter::APIQuadcopter(int newid)']]],
  ['apiquadcopter_2ecpp',['APIQuadcopter.cpp',['../APIQuadcopter_8cpp.html',1,'']]],
  ['apiquadcopter_2ehpp',['APIQuadcopter.hpp',['../APIQuadcopter_8hpp.html',1,'']]],
  ['apiquadcopterlistener',['APIQuadcopterListener',['../classkitrokopter_1_1APIQuadcopterListener.html',1,'kitrokopter']]],
  ['apiquadcopterlistener_2ehpp',['APIQuadcopterListener.hpp',['../APIQuadcopterListener_8hpp.html',1,'']]],
  ['apiquadcopterupdateevent',['APIQuadcopterUpdateEvent',['../classkitrokopter_1_1APIQuadcopterUpdateEvent.html',1,'kitrokopter']]],
  ['apiquadcopterupdateevent_2ehpp',['APIQuadcopterUpdateEvent.hpp',['../APIQuadcopterUpdateEvent_8hpp.html',1,'']]],
  ['apiwarningmessage',['apiWarningMessage',['../classkitrokopter_1_1APIMessageListener.html#aafc14807c27b1cb731cdf0fc0c772ae8',1,'kitrokopter::APIMessageListener']]]
];
